/******************************************************************************
* Exr. #7a: This Program use as the SERVER program.
*           and allows execution of 3 functions:
*           1) function that get a string, and return if its a palindrome
*           2) function that get a double number, and return if its power by 2
*           3) function that get a char, and 2 integers and return the
*              result of the char on them (e.g "+ 1 3" will return 4(= 1 + 3).
*
* =============================================================================
* Written by  	: Kfir Matityahu & Michael Shriki
* ID	 	   	: 205425960 / 305599417
* login	   	    : kfirma / michaelshr
* Course/Year   : OS1 2018
* Year	   		: B
*
* =============================================================================
* Input: Nothing.
*
* -----------------------------------------------------------------------------
* Output: Nothing.
*
* =============================================================================
******************************************************************************/

// ============================== Include ================================== //
#include <stdio.h>
#include "/usr/include/rpc/rpc.h"  //not this one, but the above: 
#include "rpc_gen.h"           /* generated by rpcgen from server_prog.x  */ 


// ============================= Functions ================================= //
//---------------------------------------------------------------------------//
// This function get a string
// Returns pointer to the result of palindrome checking (1 = true , 0 = false)
int * my_string_1_svc(char** str, struct svc_req *foo)
{
	static int result;          
 	int i;          // index for running on array

    size_t size = strlen((*str))-1;   // size of the string
    for (i = 0; i < size / 2; i++)
        if ((*str)[i] != (*str)[size - 1 - i])
            break;
	
	result = (i >= size / 2);       // we reach the middle of string
    return (&result);
}

//---------------------------------------------------------------------------//
// This function get a double number
// Returns pointer to the number by power of 2
double * my_pow_1_svc(double *x, struct svc_req *foo)
{
	static double result;          
	result = (*x) * (*x) ;

	return (&result);
}











//---------------------------------------------------------------------------//
// This function get a string (consist of operation and 2 integers)
// Returns pointer to the result of operation on these 2 integers
int * my_sum_1_svc(char** msg, struct svc_req *foo)
{     
	static int result;         /* must be static  ! */    
	char sign;              // keep the sign of the
	int n1 = 0, n2 = 0 ;    // keep the 2 numbers entered

 	sscanf(*msg, "%c %d %d",&sign, &n1, &n2 );
 
	switch (sign)           // checking the sign reade
	{
		case '+':
		    result = n1 + n2;
            break;
		case '-':
		    result = n1 - n2;
            break;
		case '/':
		    result = n1 / n2;
            break;
		case '*':
		    result = n1 * n2;
            break;
		default:
		   result = 0;
	       break;
	}

	return (&result);
} 

