/******************************************************************************
* Exr. #7b: This Program use as the CLIENT program.
*           It will run in loop, in each iteration, the program reads from the
*           user which operation he wants to do (a number in range 0-3) and the
*           right data that required for the operation. it got the value that
*           return from the server and present it to the user.
*           Runs as long as user don't ask to exit
*
* =============================================================================
* Written by  	: Kfir Matityahu & Michael Shriki
* ID	 	   	: 205425960 / 305599417
* login	   	    : kfirma / michaelshr
* Course/Year   : OS1 2018
* Year	   		: B
*
* =============================================================================
* Input: a number (0-3) of operation to do.
*
* -----------------------------------------------------------------------------
* Output: the result got from the server (number).
*
* =============================================================================
******************************************************************************/

// ============================== Include ================================== //
#include <stdio.h> 
#include "/usr/include/rpc/rpc.h" 
#include "rpc_gen.h"        /* as  generated by rpcgen */ 

// ============================== Defines ================================== //
#define BUFLEN    50         // size of the buffer message to server

// =============================== Enums =================================== //
enum MSG_TYPE_T             // type of operation user can do
{ 
  EXIT_T,
  PALINDROME_T,
  POWER_T,
  OPERATOR_T
};

// ================================ Main =================================== //
int main(int argc, char** argv) 
{     
	CLIENT *cl;              // needed for communication

    char result[BUFLEN];     // keep the result got from the server
	char* server;            // keep server ip
    char str[BUFLEN] = "";   // for keeping the string read form user
    char* str_cpy;           // for casting char[] -> char* for server function
    int msg_type;            // keep the type of operation user asks for

    // keep the answer from the server
    int* num_result;
    double* double_result;

    // check if user input has one argument (port of server)
    if (argc != 2){         
		fprintf(stderr, "Usage: %s <host ip> \n" ,argv[0]);         
		exit(EXIT_FAILURE);     
	}   
    
	server = argv[1];     // Save value of server ip

	cl = clnt_create(server, REMOTE_PROG, MESSAGEVERSS, "tcp");     
	if (cl == NULL) {    // Couldn't establish connection with server
		clnt_pcreateerror (server);             
		exit(EXIT_FAILURE);     
	}

	// -- the main loop of the client run --
	do {
		puts("===========================\n"
		     "enter your application id:\n"
		     "0. exit \n"
             "1. find if a string is palindrome \n"
		     "2. find a number power by 2 \n"
		     "3. operation on 2 integers\n");

		scanf("%d", &msg_type);

		getchar();

        switch (msg_type)
        {
            case EXIT_T:
                clnt_destroy(cl) ;
                exit(EXIT_SUCCESS);

            case PALINDROME_T :
                puts("enter a string:");
		        fgets (str, BUFLEN, stdin);
                str_cpy = &str[0];
			    num_result = my_string_1(&str_cpy, cl);
		        sprintf(result, "%d", *num_result);
                break;

            case POWER_T:
                puts("enter a double number:");
			    double x;
		        scanf("%lf", &x);
			    double_result = my_pow_1(&x, cl);
			    sprintf(result, "%lf", *double_result);
                break;

            case OPERATOR_T:
                puts("enter: operation code, integer A , integer B");
                fgets (str, BUFLEN, stdin);
                str_cpy = &str[0];
                num_result = my_sum_1(&str_cpy, cl);
		        sprintf(result, "%d", *num_result);
                break;

            default:
                break;
        }

		if (result == NULL)  // couldn't establish connection with server.
        {					  // call failed
            
			clnt_perror (cl, server);         
			exit(EXIT_FAILURE);     
		} 

		printf("Result returned from server is: %s\n\n", result) ;

    } while (1);
 
    return (EXIT_SUCCESS);
}

